language: ruby

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "gem update --system 2.6.12"
  - "gem update bundler"

script:
  - rake test

rvm:
  - 2.3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
